/*
Object.values = retorna valores do objeto...
Object.entries =  retorna as entradas (chaves, valores) em arrays do objeto...
Object.getOwnPropertyDescriptor = retorna o estado de privacidade do objeto...
Object.asing({}, objeto) = atribui outro objeto ao objeto criado...

Object.keys = retorna as chaves do objeto...
Object.freze = congela o objeto...
Object.defineProperties = define varias propriedades...
Object.defineProperty = define uma propriedade...
*/

// const produto = { nome: 'Produto', preco: 1.8 };
// const caneca = Object.assign({}, produto, { material: 'Porcelana' });

// caneca.nome = 'Outro nome';
// caneca.preco = 2.5;
// console.log(produto);
// console.log(caneca);

const produto = { nome: 'Produto', preco: 1.8, material: 'Porcelana' };

for (let [chave, valor] of Object.entries(produto)) { //let chave primeiro el do array retornado e o valor segundo elemento.
    console.log(chave, valor);
}